apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
      - image: asia-northeast3-docker.pkg.dev/phonic-monolith-388113/reservations/production
        name: production
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: PORT
            value: '3004'
          - name: AUTH_HOST
            value: auth-tcp
          - name: AUTH_PORT
            value: '3002'
          - name: PAYMENTS_HOST
            value: payments
          - name: PAYMENTS_PORT
            value: '3001'
        ports:
          - containerPort: 3004